groups:
  - name: MinioAlert
    rules:
    - alert: MinioServiceDown
      expr: minio_version_info == 0
      for: 30s
      labels: 
        severity: critical
      annotations: 
        summary: "instance: {{ $labels.instance }} minio服务故障"
        value: "{{ $value }}"

    - alert: MinioDisksOffline
      expr: minio_disks_offline >= 1
      for: 45s
      labels:
        severity: warning
      annotations:
        summary: "{{ $labels.instance }} minio集群有磁盘故障"
        value: "{{ $value }}"
