{
 "title": "资源TOP",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "origin_prometheus",
    "label": "数据源",
    "query": "label_values(origin_prometheus)"
   },
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\"}, job)"
   },
   {
    "name": "hostname",
    "label": "主机名",
    "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "Instance",
    "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "maxmount",
    "label": "最大挂载目录",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",instance=~'$node',fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
   },
   {
    "name": "show_hostname",
    "label": "展示使用的主机名",
    "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",instance=~\"$node\"}, nodename)"
   },
   {
    "name": "total",
    "label": "主机数",
    "query": "query_result(count(node_uname_info{origin_prometheus=~\"$origin_prometheus\"}))"
   },
   { "name": "TOP_NUM", "label": "TOP", "query": "10,20,30,50,100" }
  ]
 },
 "panels": [
  { "title": "CPU资源TOP${TOP_NUM}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU利用率",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "topk(${TOP_NUM},((avg by (environment,instance,job) (irate(node_cpu_seconds_total{client=~\"node\",mode=\"user\"}[5m])))  * 100))",
     "legendFormat": "内存使用率"
    }
   ]
  },
  {
   "title": "1分钟负载",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "targets": [
    { "expr": "topk(${TOP_NUM},(node_load1))", "legendFormat": "CPU核数" }
   ]
  },
  {
   "title": "5分钟负载",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "targets": [
    { "expr": "topk(${TOP_NUM},(node_load5))", "legendFormat": "CPU核数" }
   ]
  },
  { "title": "内存资源TOP${TOP_NUM}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "内存利用率",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "topk(${TOP_NUM},((1 - (node_memory_MemAvailable_bytes/ (node_memory_MemTotal_bytes)))* 100))",
     "legendFormat": "内存使用率"
    }
   ]
  },
  {
   "title": "剩余可用内存(最小)",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "bottomk(${TOP_NUM},node_memory_MemAvailable_bytes)",
     "legendFormat": "可用内存"
    }
   ]
  },
  {
   "title": "已用内存",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "topk(${TOP_NUM},node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)",
     "legendFormat": "已用内存"
    }
   ]
  },
  { "title": "磁盘资源TOP${TOP_NUM}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "磁盘使用率",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "topk(${TOP_NUM},((1 - node_filesystem_avail_bytes{fstype=~\"ext.*|xfs\"} / node_filesystem_size_bytes{fstype=~\"ext.*|xfs\"}) * 100))",
     "legendFormat": "磁盘使用率"
    }
   ]
  },
  {
   "title": "磁盘可用空间(最小)",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 23 },
   "targets": [
    {
     "expr": "bottomk(${TOP_NUM},node_filesystem_avail_bytes {fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*|.*boot.*\"}-0)"
    }
   ]
  },
  { "title": "网络资源TOP${TOP_NUM}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "网卡下行流量",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "topk(${TOP_NUM},(rate(node_network_receive_bytes_total[30s])*8))",
     "legendFormat": "磁盘使用率"
    }
   ]
  },
  {
   "title": "TOP10-网卡上行流量",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 11, "y": 34 },
   "targets": [
    {
     "expr": "topk(${TOP_NUM},((rate(node_network_transmit_bytes_total[1m])*8)))"
    }
   ]
  },
  {
   "title": "TCP连接数",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "topk(${TOP_NUM},(node_netstat_Tcp_CurrEstab))",
     "legendFormat": "TCP连接数"
    }
   ]
  }
 ]
}